defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "pages"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"

paginate: 10
paginate_path: "page:num"

markdown: redcarpet
redcarpet:
    extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
